### ISSUE TITLE
How to train an Unkown Label Image

### ISSUE THREAD

**Issue by cjkini** [meeki007/node-red-contrib-facial-recognition#20]
Hi guys.

I have been experimenting this node for a week and the result is fantastic. This node can recognize person face only with 3 or 4 label images. However, I realize that everytime I load the unknown image (i.e : image that hasnt been label yet) it always return any one of those label images that i set at the folder. I try to set one folder with label unknown where the folder doesnt contain any images, still the node will recognize on of those label images.

Any idea how I can solve this thing out?

Tq.

**Comment by meeki007** [comment]
Hey cjini,

glad you like it and i hope i can help you.
I don't think I fully understand the issue / question. 

I think you want to add your own photos to detect your own provided images?
can you break your issue into multiple parts? 

if you load a unknown image it will try to find a face that matches based on the folder images you have provided. Based on the confidence threshold it will match or not match.

**Comment by cjkini** [comment]
Hi @meeki007 ,
Thanks for replying me here :) 

My problem is how do we set this recognition nodes to recognize an unknown person. For example, I have folder of Alice, Bob and Smith. During the test/operation, a guy named Samuel came in front camera and take a picture. SInce this guy is a new guy and we dont have label for him yet, what we can do so that this node will recognize this new guy as unknown. 

What is happening now during the test, when Samuel came, the node still recognize him as one of those labeled name either Alice or Bob or Smith. I think the right result will be as unknown. So in essence, this setup should be able to recognize Alice, Bob, Smith as well as Unknown at the annotate box.

I am trying to use this node where I can implement at home door or office door where I can be notified with known person (labeled folder) or unknown person (not labeled yet folder) when they are at in front of the door camera. Hope this clarify my question :)

**Comment by meeki007** [comment]
I think I figured this one out.
So It will always try to find the best match. its based on confidence level.

So you will have to make your own rule to filter out based on confidence. If its only 0.2 then its most likely not a person in your folder.
