### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by thejollypop** [meeki007/node-red-contrib-facial-recognition#8]
Hi meeki007:)
Great work, I'm looking for this face recognition capabilities for a long time...

I've installed on Windows Python 3.9.1 (and Python 2.7) and all TensorFlow's dependencies. 
Did everything in the [Windows troubleshooting guide](https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md) and re-installed 'npm i @tensorflow/tfjs-node'
but still unable to run on Windows:

![image](https://user-images.githubusercontent.com/75426675/102052726-31634700-3def-11eb-9eb5-22cbdb847da8.png)

Maybe it's TensorFlow/Python 2.X related. Maybe not. Any ideas? Thanks!

**Comment by meeki007** [comment]
I will try to help ya. Know upfront when windows 2003 came out I went "NOPE" and have never looked back. So its going to be allot of stuff I suggest that may not work / or break your node red install.

If your okay with that ill press forward.

Else have you thought about installing a docker instance of node-red ???? I bet it would work in docker

**Comment by meeki007** [comment]
in the feture please copy and paste the error txt so I can copy paste it VS having to type it :)

however just reading it I think i know what happened.

the Windows troubleshooting is telling you to install every ting to your default dir. You need to run the commands to install it from within the node-red dir

run all the commands in the Windows troubleshooting guide from within your Node-RED user directory - typically ~/.node-red

**Comment by thejollypop** [comment]
Hi meeki007 :)Thanks for the prompt response. 
I've reinstalled everything but it might be a conflict with my other tensorflow-related packages installed, like: 
node-red-contrib-tfjs-coco-ssd or maybe not. 
I'll try to troubleshoot it deeper, and see if I can get insights. Anyways, I believe we can close this thread. 
Keep on rockin!
